### ISSUE TITLE
Improvements to-do

### ISSUE THREAD

**Issue by jdrydn** [someimportantcompany/status-page#1]
## Customisation
- [ ] Cover image on top-half of page, similar to how Notion does it.
![Screenshot 2020-03-21 at 00 30 41](https://user-images.githubusercontent.com/406967/77215312-5dc18f80-6b0b-11ea-9ebb-400e435cfccd.png)
- [ ] Support for emojis as icons in components 📱🖥🚨

## Integrations support
- [x] Current status JSON
- [ ] Current status JSON documentation
- [ ] Current status RSS feed?
- [ ] History JSON?
- [x] History RSS feed
- [ ] History RSS feed documentation

## Examples
- [ ] [Car Throttle](https://carthrottle.com) example
- [ ] [muzmatch](https://muzmatch.com) example
- [ ] [Pied Piper](https://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)) example
- [ ] [Mythic Quest](https://en.wikipedia.org/wiki/Mythic_Quest:_Raven%27s_Banquet) example
